// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminCodesFieldNames          = builder.RawFieldNames(&AdminCodes{})
	adminCodesRows                = strings.Join(adminCodesFieldNames, ",")
	adminCodesRowsExpectAutoSet   = strings.Join(stringx.Remove(adminCodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminCodesRowsWithPlaceHolder = strings.Join(stringx.Remove(adminCodesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	adminCodesModel interface {
		Insert(ctx context.Context, data *AdminCodes) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminCodes, error)
		FindOneByCode(ctx context.Context, code string) (*AdminCodes, error)
		Update(ctx context.Context, data *AdminCodes) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminCodesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AdminCodes struct {
		Id        int64        `db:"id"`         // Admin Code ID
		Code      string       `db:"code"`       // The actual admin code
		CreatedAt time.Time    `db:"created_at"` // Creation time
		Used      int64        `db:"used"`       // is code used
		ExpiredAt sql.NullTime `db:"expired_at"` // code expired time
	}
)

func newAdminCodesModel(conn sqlx.SqlConn) *defaultAdminCodesModel {
	return &defaultAdminCodesModel{
		conn:  conn,
		table: "`admin_codes`",
	}
}

func (m *defaultAdminCodesModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAdminCodesModel) FindOne(ctx context.Context, id int64) (*AdminCodes, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminCodesRows, m.table)
	var resp AdminCodes
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminCodesModel) FindOneByCode(ctx context.Context, code string) (*AdminCodes, error) {
	var resp AdminCodes
	query := fmt.Sprintf("select %s from %s where `code` = ? limit 1", adminCodesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, code)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminCodesModel) Insert(ctx context.Context, data *AdminCodes) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, adminCodesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Code, data.Used, data.ExpiredAt)
	return ret, err
}

func (m *defaultAdminCodesModel) Update(ctx context.Context, newData *AdminCodes) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminCodesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Code, newData.Used, newData.ExpiredAt, newData.Id)
	return err
}

func (m *defaultAdminCodesModel) tableName() string {
	return m.table
}
