// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loginHistoryFieldNames          = builder.RawFieldNames(&LoginHistory{})
	loginHistoryRows                = strings.Join(loginHistoryFieldNames, ",")
	loginHistoryRowsExpectAutoSet   = strings.Join(stringx.Remove(loginHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loginHistoryRowsWithPlaceHolder = strings.Join(stringx.Remove(loginHistoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserServiceLoginHistoryIdPrefix = "cache:userService:loginHistory:id:"
)

type (
	loginHistoryModel interface {
		Insert(ctx context.Context, data *LoginHistory) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*LoginHistory, error)
		Update(ctx context.Context, data *LoginHistory) error
		Delete(ctx context.Context, id int64) error
	}

	defaultLoginHistoryModel struct {
		sqlc.CachedConn
		table string
	}

	LoginHistory struct {
		Id        int64          `db:"id"`         // Login history ID
		UserId    int64          `db:"user_id"`    // User ID
		LoginTime time.Time      `db:"login_time"` // Login time
		LoginIp   sql.NullString `db:"login_ip"`
	}
)

func newLoginHistoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLoginHistoryModel {
	return &defaultLoginHistoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`login_history`",
	}
}

func (m *defaultLoginHistoryModel) Delete(ctx context.Context, id int64) error {
	userServiceLoginHistoryIdKey := fmt.Sprintf("%s%v", cacheUserServiceLoginHistoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userServiceLoginHistoryIdKey)
	return err
}

func (m *defaultLoginHistoryModel) FindOne(ctx context.Context, id int64) (*LoginHistory, error) {
	userServiceLoginHistoryIdKey := fmt.Sprintf("%s%v", cacheUserServiceLoginHistoryIdPrefix, id)
	var resp LoginHistory
	err := m.QueryRowCtx(ctx, &resp, userServiceLoginHistoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginHistoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoginHistoryModel) Insert(ctx context.Context, data *LoginHistory) (sql.Result, error) {
	userServiceLoginHistoryIdKey := fmt.Sprintf("%s%v", cacheUserServiceLoginHistoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, loginHistoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.LoginTime, data.LoginIp)
	}, userServiceLoginHistoryIdKey)
	return ret, err
}

func (m *defaultLoginHistoryModel) Update(ctx context.Context, data *LoginHistory) error {
	userServiceLoginHistoryIdKey := fmt.Sprintf("%s%v", cacheUserServiceLoginHistoryIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, loginHistoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserId, data.LoginTime, data.LoginIp, data.Id)
	}, userServiceLoginHistoryIdKey)
	return err
}

func (m *defaultLoginHistoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserServiceLoginHistoryIdPrefix, primary)
}

func (m *defaultLoginHistoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", loginHistoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLoginHistoryModel) tableName() string {
	return m.table
}
