// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.3

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	usersFieldNames          = builder.RawFieldNames(&Users{})
	usersRows                = strings.Join(usersFieldNames, ",")
	usersRowsExpectAutoSet   = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	usersRowsWithPlaceHolder = strings.Join(stringx.Remove(usersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheUserServiceUsersIdPrefix       = "cache:userService:users:id:"
	cacheUserServiceUsersEmailPrefix    = "cache:userService:users:email:"
	cacheUserServiceUsersPhonePrefix    = "cache:userService:users:phone:"
	cacheUserServiceUsersUsernamePrefix = "cache:userService:users:username:"
)

type (
	usersModel interface {
		Insert(ctx context.Context, data *Users) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Users, error)
		FindOneByEmail(ctx context.Context, email string) (*Users, error)
		FindOneByPhone(ctx context.Context, phone string) (*Users, error)
		FindOneByUsername(ctx context.Context, username string) (*Users, error)
		Update(ctx context.Context, data *Users) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUsersModel struct {
		sqlc.CachedConn
		table string
	}

	Users struct {
		Id        int64          `db:"id"`         // User ID
		Username  string         `db:"username"`   // Username
		Password  string         `db:"password"`   // Password (hashed)
		Email     string         `db:"email"`      // Email address
		Phone     string         `db:"phone"`      // Phone number
		Avatar    sql.NullString `db:"avatar"`     // User avatar URL
		Role      string         `db:"role"`       // User role
		CreatedAt time.Time      `db:"created_at"` // Creation time
		UpdatedAt time.Time      `db:"updated_at"` // Last update time
	}
)

func newUsersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultUsersModel {
	return &defaultUsersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`users`",
	}
}

func (m *defaultUsersModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	userServiceUsersEmailKey := fmt.Sprintf("%s%v", cacheUserServiceUsersEmailPrefix, data.Email)
	userServiceUsersIdKey := fmt.Sprintf("%s%v", cacheUserServiceUsersIdPrefix, id)
	userServiceUsersPhoneKey := fmt.Sprintf("%s%v", cacheUserServiceUsersPhonePrefix, data.Phone)
	userServiceUsersUsernameKey := fmt.Sprintf("%s%v", cacheUserServiceUsersUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, userServiceUsersEmailKey, userServiceUsersIdKey, userServiceUsersPhoneKey, userServiceUsersUsernameKey)
	return err
}

func (m *defaultUsersModel) FindOne(ctx context.Context, id int64) (*Users, error) {
	userServiceUsersIdKey := fmt.Sprintf("%s%v", cacheUserServiceUsersIdPrefix, id)
	var resp Users
	err := m.QueryRowCtx(ctx, &resp, userServiceUsersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", usersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByEmail(ctx context.Context, email string) (*Users, error) {
	userServiceUsersEmailKey := fmt.Sprintf("%s%v", cacheUserServiceUsersEmailPrefix, email)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, userServiceUsersEmailKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, email); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByPhone(ctx context.Context, phone string) (*Users, error) {
	userServiceUsersPhoneKey := fmt.Sprintf("%s%v", cacheUserServiceUsersPhonePrefix, phone)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, userServiceUsersPhoneKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `phone` = ? limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, phone); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	userServiceUsersUsernameKey := fmt.Sprintf("%s%v", cacheUserServiceUsersUsernamePrefix, username)
	var resp Users
	err := m.QueryRowIndexCtx(ctx, &resp, userServiceUsersUsernameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `username` = ? limit 1", usersRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, username); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	userServiceUsersEmailKey := fmt.Sprintf("%s%v", cacheUserServiceUsersEmailPrefix, data.Email)
	userServiceUsersIdKey := fmt.Sprintf("%s%v", cacheUserServiceUsersIdPrefix, data.Id)
	userServiceUsersPhoneKey := fmt.Sprintf("%s%v", cacheUserServiceUsersPhonePrefix, data.Phone)
	userServiceUsersUsernameKey := fmt.Sprintf("%s%v", cacheUserServiceUsersUsernamePrefix, data.Username)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, usersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Username, data.Password, data.Email, data.Phone, data.Avatar, data.Role)
	}, userServiceUsersEmailKey, userServiceUsersIdKey, userServiceUsersPhoneKey, userServiceUsersUsernameKey)
	return ret, err
}

func (m *defaultUsersModel) Update(ctx context.Context, newData *Users) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	userServiceUsersEmailKey := fmt.Sprintf("%s%v", cacheUserServiceUsersEmailPrefix, data.Email)
	userServiceUsersIdKey := fmt.Sprintf("%s%v", cacheUserServiceUsersIdPrefix, data.Id)
	userServiceUsersPhoneKey := fmt.Sprintf("%s%v", cacheUserServiceUsersPhonePrefix, data.Phone)
	userServiceUsersUsernameKey := fmt.Sprintf("%s%v", cacheUserServiceUsersUsernamePrefix, data.Username)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, usersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.Username, newData.Password, newData.Email, newData.Phone, newData.Avatar, newData.Role, newData.Id)
	}, userServiceUsersEmailKey, userServiceUsersIdKey, userServiceUsersPhoneKey, userServiceUsersUsernameKey)
	return err
}

func (m *defaultUsersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheUserServiceUsersIdPrefix, primary)
}

func (m *defaultUsersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", usersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUsersModel) tableName() string {
	return m.table
}
