// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: reply.proto

package reply

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReplyService_GetReplies_FullMethodName  = "/reply.ReplyService/GetReplies"
	ReplyService_GetReply_FullMethodName    = "/reply.ReplyService/GetReply"
	ReplyService_AddReply_FullMethodName    = "/reply.ReplyService/AddReply"
	ReplyService_EditReply_FullMethodName   = "/reply.ReplyService/EditReply"
	ReplyService_DeleteReply_FullMethodName = "/reply.ReplyService/DeleteReply"
)

// ReplyServiceClient is the client API for ReplyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReplyServiceClient interface {
	GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*GetRepliesResponse, error)
	GetReply(ctx context.Context, in *GetReplyRequest, opts ...grpc.CallOption) (*Reply, error)
	AddReply(ctx context.Context, in *AddReplyRequest, opts ...grpc.CallOption) (*Empty, error)
	EditReply(ctx context.Context, in *EditReplyRequest, opts ...grpc.CallOption) (*Empty, error)
	DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*Empty, error)
}

type replyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReplyServiceClient(cc grpc.ClientConnInterface) ReplyServiceClient {
	return &replyServiceClient{cc}
}

func (c *replyServiceClient) GetReplies(ctx context.Context, in *GetRepliesRequest, opts ...grpc.CallOption) (*GetRepliesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRepliesResponse)
	err := c.cc.Invoke(ctx, ReplyService_GetReplies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyServiceClient) GetReply(ctx context.Context, in *GetReplyRequest, opts ...grpc.CallOption) (*Reply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reply)
	err := c.cc.Invoke(ctx, ReplyService_GetReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyServiceClient) AddReply(ctx context.Context, in *AddReplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReplyService_AddReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyServiceClient) EditReply(ctx context.Context, in *EditReplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReplyService_EditReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replyServiceClient) DeleteReply(ctx context.Context, in *DeleteReplyRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, ReplyService_DeleteReply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplyServiceServer is the server API for ReplyService service.
// All implementations must embed UnimplementedReplyServiceServer
// for forward compatibility.
type ReplyServiceServer interface {
	GetReplies(context.Context, *GetRepliesRequest) (*GetRepliesResponse, error)
	GetReply(context.Context, *GetReplyRequest) (*Reply, error)
	AddReply(context.Context, *AddReplyRequest) (*Empty, error)
	EditReply(context.Context, *EditReplyRequest) (*Empty, error)
	DeleteReply(context.Context, *DeleteReplyRequest) (*Empty, error)
	mustEmbedUnimplementedReplyServiceServer()
}

// UnimplementedReplyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReplyServiceServer struct{}

func (UnimplementedReplyServiceServer) GetReplies(context.Context, *GetRepliesRequest) (*GetRepliesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReplies not implemented")
}
func (UnimplementedReplyServiceServer) GetReply(context.Context, *GetReplyRequest) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReply not implemented")
}
func (UnimplementedReplyServiceServer) AddReply(context.Context, *AddReplyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddReply not implemented")
}
func (UnimplementedReplyServiceServer) EditReply(context.Context, *EditReplyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditReply not implemented")
}
func (UnimplementedReplyServiceServer) DeleteReply(context.Context, *DeleteReplyRequest) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteReply not implemented")
}
func (UnimplementedReplyServiceServer) mustEmbedUnimplementedReplyServiceServer() {}
func (UnimplementedReplyServiceServer) testEmbeddedByValue()                      {}

// UnsafeReplyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReplyServiceServer will
// result in compilation errors.
type UnsafeReplyServiceServer interface {
	mustEmbedUnimplementedReplyServiceServer()
}

func RegisterReplyServiceServer(s grpc.ServiceRegistrar, srv ReplyServiceServer) {
	// If the following call pancis, it indicates UnimplementedReplyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReplyService_ServiceDesc, srv)
}

func _ReplyService_GetReplies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRepliesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).GetReplies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyService_GetReplies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).GetReplies(ctx, req.(*GetRepliesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplyService_GetReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).GetReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyService_GetReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).GetReply(ctx, req.(*GetReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplyService_AddReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).AddReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyService_AddReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).AddReply(ctx, req.(*AddReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplyService_EditReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).EditReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyService_EditReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).EditReply(ctx, req.(*EditReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplyService_DeleteReply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteReplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplyServiceServer).DeleteReply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReplyService_DeleteReply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplyServiceServer).DeleteReply(ctx, req.(*DeleteReplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReplyService_ServiceDesc is the grpc.ServiceDesc for ReplyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReplyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reply.ReplyService",
	HandlerType: (*ReplyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReplies",
			Handler:    _ReplyService_GetReplies_Handler,
		},
		{
			MethodName: "GetReply",
			Handler:    _ReplyService_GetReply_Handler,
		},
		{
			MethodName: "AddReply",
			Handler:    _ReplyService_AddReply_Handler,
		},
		{
			MethodName: "EditReply",
			Handler:    _ReplyService_EditReply_Handler,
		},
		{
			MethodName: "DeleteReply",
			Handler:    _ReplyService_DeleteReply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reply.proto",
}
